# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
######################
# General Setting
######################

  config.vm.box = "rockylinux/9"
  config.vm.hostname = "wb01"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.31" #Host only NW
###
  config.vm.provider "virtualbox" do |vb|
    # supress CPU 100% when return from sleep
    vb.customize ["modifyvm", :id, "--audio", "none"]
    vb.gui = false
    vb.cpus = 1
    vb.memory = 512
  end
  # Folderの同期、うまくいかないのでコメントアウト
#  config.vm.synced_folder "", "/public"
#######################
# VMの設定変更
#######################
##  config.vm.provision "shell", inline: $script_common_vm
##
end

########################
# Script
########################
$script_common_vm = <<-SCRIPT
### allow remote login
sed -i -e 's/^#PermitRootLogin yes/PermitRootLogin yes/g' /etc/ssh/sshd_config
sed -i -e 's/^PasswordAuthentication no/PasswordAuthentication yes/g' /etc/ssh/sshd_config
systemctl restart sshd

### access yum repository at CentOS8
#sed -i -e 's/^mirrorlist/#mirrorlist/g' /etc/yum.repos.d/CentOS-Linux-*
#sed -i -e 's|^#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-Linux-*

### install japanese langpack
dnf install -y glibc-langpack-ja
localectl set-locale ja_JP.utf8

### create user
adduser koseki
passwd koseki << EOF
pwkoseki
pwkoseki
EOF
usermod -G wheel koseki
SCRIPT

#############################
#### script_common_hosts
#############################
$script_common_hosts = <<-SCRIPT
cat << END > /etc/hosts
127.0.0.1   localhost localhost.localdomain
10.187.131.132 agdn01
10.187.131.133 agdn02
10.187.131.148 agot01
10.187.131.149 agot02
END
SCRIPT


