# -*- mode: ruby -*-
# vi: set ft=ruby :

# 外部ファイル読み込み
require 'yaml'

vim_conf = YAML.load_file '../conf/vim_conf_rocky.yaml'
os_conf = YAML.load_file '../conf/os_conf_rocky.yaml'

Vagrant.configure("2") do |config|
######################
# General Setting
######################

  config.vm.box = "rockylinux/9"
  config.vm.hostname = "sv11"
  config.vm.box_check_update = false
  config.vm.network "private_network", ip: "192.168.56.11" #Host only NW
###
  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 1
    vb.memory = 512
  end
  config.vm.synced_folder "../pub/", "/pub"
  config.vm.synced_folder "../work/", "/home/vagrant/work"
#######################
# OS設定
  config.vm.provision "shell", inline: os_conf['os']['timezone']
  config.vm.provision "shell", inline: os_conf['os']['locale']
# vimの設定
  config.vm.provision "shell", inline: vim_conf['install']['vim']
  config.vm.provision "shell", inline: vim_conf['setting']['vimrc']
#######################
end
